// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231129101532_migr")]
    partial class migr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06Shop.Shared.Shop.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FilmDetailsId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "5",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 709.097133107994m,
                            ReleaseDate = new DateTime(2023, 1, 11, 11, 42, 51, 536, DateTimeKind.Local).AddTicks(9371),
                            Title = "ut"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 395.001609376632m,
                            ReleaseDate = new DateTime(2023, 4, 22, 7, 3, 54, 274, DateTimeKind.Local).AddTicks(8605),
                            Title = "quo"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "3",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 702.518694762382m,
                            ReleaseDate = new DateTime(2023, 5, 28, 19, 22, 23, 33, DateTimeKind.Local).AddTicks(2658),
                            Title = "repudiandae"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "4",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 693.668755019395m,
                            ReleaseDate = new DateTime(2022, 12, 2, 11, 18, 14, 402, DateTimeKind.Local).AddTicks(2027),
                            Title = "voluptatem"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "7",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 526.029559857226m,
                            ReleaseDate = new DateTime(2023, 11, 24, 3, 38, 3, 806, DateTimeKind.Local).AddTicks(8727),
                            Title = "esse"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "0",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 245.962609125284m,
                            ReleaseDate = new DateTime(2022, 12, 3, 2, 54, 18, 162, DateTimeKind.Local).AddTicks(3756),
                            Title = "fuga"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "5",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 57.7898492826102m,
                            ReleaseDate = new DateTime(2023, 2, 8, 10, 21, 5, 268, DateTimeKind.Local).AddTicks(2853),
                            Title = "ipsa"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "9",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 988.892659404265m,
                            ReleaseDate = new DateTime(2023, 8, 13, 9, 5, 32, 31, DateTimeKind.Local).AddTicks(8805),
                            Title = "fuga"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "3",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 223.882037785315m,
                            ReleaseDate = new DateTime(2023, 7, 21, 23, 53, 44, 185, DateTimeKind.Local).AddTicks(6633),
                            Title = "dolor"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "3",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 476.020144769466m,
                            ReleaseDate = new DateTime(2023, 5, 3, 22, 36, 8, 635, DateTimeKind.Local).AddTicks(4987),
                            Title = "et"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "9",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 594.964523955232m,
                            ReleaseDate = new DateTime(2023, 1, 24, 21, 1, 36, 918, DateTimeKind.Local).AddTicks(2439),
                            Title = "dolore"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "9",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 312.227141921049m,
                            ReleaseDate = new DateTime(2023, 4, 7, 9, 32, 48, 107, DateTimeKind.Local).AddTicks(9571),
                            Title = "aspernatur"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "4",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 618.358974748924m,
                            ReleaseDate = new DateTime(2023, 9, 30, 19, 5, 48, 821, DateTimeKind.Local).AddTicks(303),
                            Title = "aspernatur"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "0",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 80.6260295047546m,
                            ReleaseDate = new DateTime(2023, 1, 27, 9, 3, 51, 197, DateTimeKind.Local).AddTicks(2458),
                            Title = "fuga"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 471.610621951339m,
                            ReleaseDate = new DateTime(2022, 12, 14, 2, 37, 44, 271, DateTimeKind.Local).AddTicks(5183),
                            Title = "nesciunt"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "4",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 366.261149519245m,
                            ReleaseDate = new DateTime(2023, 11, 25, 6, 45, 22, 737, DateTimeKind.Local).AddTicks(8267),
                            Title = "commodi"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "8",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 271.938482550876m,
                            ReleaseDate = new DateTime(2022, 12, 18, 10, 34, 59, 421, DateTimeKind.Local).AddTicks(8712),
                            Title = "ut"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 461.718092748764m,
                            ReleaseDate = new DateTime(2022, 12, 12, 8, 47, 58, 923, DateTimeKind.Local).AddTicks(835),
                            Title = "omnis"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "4",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 319.251068810584m,
                            ReleaseDate = new DateTime(2023, 6, 20, 11, 3, 24, 100, DateTimeKind.Local).AddTicks(5035),
                            Title = "earum"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "0",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 612.278680905364m,
                            ReleaseDate = new DateTime(2023, 2, 28, 22, 48, 14, 928, DateTimeKind.Local).AddTicks(4306),
                            Title = "consequuntur"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "8",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 814.14169213648m,
                            ReleaseDate = new DateTime(2023, 4, 25, 23, 25, 9, 923, DateTimeKind.Local).AddTicks(7828),
                            Title = "voluptates"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "8",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 822.374616404238m,
                            ReleaseDate = new DateTime(2023, 10, 11, 4, 12, 0, 614, DateTimeKind.Local).AddTicks(9520),
                            Title = "sint"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "4",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 654.18977049747m,
                            ReleaseDate = new DateTime(2023, 4, 2, 2, 43, 34, 339, DateTimeKind.Local).AddTicks(5292),
                            Title = "sunt"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "7",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 738.155003849489m,
                            ReleaseDate = new DateTime(2023, 11, 12, 15, 49, 10, 387, DateTimeKind.Local).AddTicks(9290),
                            Title = "molestiae"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "1",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 43.6775831215445m,
                            ReleaseDate = new DateTime(2023, 6, 8, 11, 13, 22, 5, DateTimeKind.Local).AddTicks(5045),
                            Title = "et"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "7",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 507.616215421639m,
                            ReleaseDate = new DateTime(2023, 11, 21, 20, 27, 21, 105, DateTimeKind.Local).AddTicks(3768),
                            Title = "laboriosam"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "2",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 910.785444308438m,
                            ReleaseDate = new DateTime(2023, 7, 27, 6, 57, 38, 927, DateTimeKind.Local).AddTicks(6701),
                            Title = "velit"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "3",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 84.0327789569426m,
                            ReleaseDate = new DateTime(2022, 12, 19, 12, 46, 30, 327, DateTimeKind.Local).AddTicks(5310),
                            Title = "suscipit"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "4",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 660.05177966694m,
                            ReleaseDate = new DateTime(2023, 7, 22, 4, 56, 41, 145, DateTimeKind.Local).AddTicks(8801),
                            Title = "et"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "4",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 430.155933462156m,
                            ReleaseDate = new DateTime(2023, 6, 7, 17, 41, 35, 411, DateTimeKind.Local).AddTicks(7569),
                            Title = "nobis"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "9",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 126.71586487755m,
                            ReleaseDate = new DateTime(2023, 4, 21, 13, 14, 49, 121, DateTimeKind.Local).AddTicks(9466),
                            Title = "facilis"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "8",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 150.158714624196m,
                            ReleaseDate = new DateTime(2022, 12, 8, 2, 2, 3, 53, DateTimeKind.Local).AddTicks(3303),
                            Title = "occaecati"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "6",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 3.84736985426739m,
                            ReleaseDate = new DateTime(2023, 2, 21, 1, 0, 1, 100, DateTimeKind.Local).AddTicks(2745),
                            Title = "at"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "6",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 645.993864636865m,
                            ReleaseDate = new DateTime(2023, 3, 18, 1, 32, 4, 935, DateTimeKind.Local).AddTicks(3469),
                            Title = "qui"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 289.121948837359m,
                            ReleaseDate = new DateTime(2023, 10, 8, 22, 12, 16, 399, DateTimeKind.Local).AddTicks(8876),
                            Title = "corrupti"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "3",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 255.49067058018m,
                            ReleaseDate = new DateTime(2023, 8, 14, 22, 11, 54, 67, DateTimeKind.Local).AddTicks(6838),
                            Title = "maxime"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "1",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 118.585349240147m,
                            ReleaseDate = new DateTime(2022, 11, 30, 11, 0, 6, 878, DateTimeKind.Local).AddTicks(2959),
                            Title = "est"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "4",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 857.801498141979m,
                            ReleaseDate = new DateTime(2023, 2, 23, 2, 57, 25, 970, DateTimeKind.Local).AddTicks(5955),
                            Title = "tenetur"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "0",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 456.989796488541m,
                            ReleaseDate = new DateTime(2023, 2, 25, 17, 38, 26, 837, DateTimeKind.Local).AddTicks(4333),
                            Title = "natus"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "3",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 383.278243241961m,
                            ReleaseDate = new DateTime(2022, 12, 18, 22, 39, 20, 531, DateTimeKind.Local).AddTicks(4332),
                            Title = "impedit"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "3",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 729.819554187274m,
                            ReleaseDate = new DateTime(2023, 3, 16, 12, 11, 36, 274, DateTimeKind.Local).AddTicks(5967),
                            Title = "et"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "7",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 12.9330949308039m,
                            ReleaseDate = new DateTime(2023, 9, 1, 21, 20, 18, 506, DateTimeKind.Local).AddTicks(5034),
                            Title = "aperiam"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 32.5958482886645m,
                            ReleaseDate = new DateTime(2023, 7, 5, 12, 26, 7, 139, DateTimeKind.Local).AddTicks(4421),
                            Title = "officiis"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 342.748452510102m,
                            ReleaseDate = new DateTime(2023, 5, 4, 2, 55, 37, 537, DateTimeKind.Local).AddTicks(6851),
                            Title = "id"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 158.364214679396m,
                            ReleaseDate = new DateTime(2023, 7, 18, 9, 22, 23, 583, DateTimeKind.Local).AddTicks(4228),
                            Title = "animi"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "5",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 515.594907488485m,
                            ReleaseDate = new DateTime(2023, 4, 28, 13, 28, 14, 571, DateTimeKind.Local).AddTicks(6983),
                            Title = "similique"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "0",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 927.287084065046m,
                            ReleaseDate = new DateTime(2023, 8, 17, 0, 54, 53, 978, DateTimeKind.Local).AddTicks(1095),
                            Title = "provident"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "7",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 674.987207627849m,
                            ReleaseDate = new DateTime(2022, 12, 15, 9, 29, 58, 378, DateTimeKind.Local).AddTicks(3935),
                            Title = "ut"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "9",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 69.0171712734816m,
                            ReleaseDate = new DateTime(2023, 2, 16, 10, 27, 54, 105, DateTimeKind.Local).AddTicks(4314),
                            Title = "nulla"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 890.001594146714m,
                            ReleaseDate = new DateTime(2023, 7, 26, 15, 27, 14, 349, DateTimeKind.Local).AddTicks(2038),
                            Title = "sint"
                        });
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.FilmDetails", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("Manufactuer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FilmId");

                    b.ToTable("FilmDetails");
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.FilmSuppliers", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("FilmId", "SupplierId");

                    b.HasIndex("SupplierId");

                    b.ToTable("FilmSuppliers");
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContantEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.Film", b =>
                {
                    b.HasOne("P06Shop.Shared.Shop.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.FilmDetails", b =>
                {
                    b.HasOne("P06Shop.Shared.Shop.Film", "Film")
                        .WithOne("FilmDetails")
                        .HasForeignKey("P06Shop.Shared.Shop.FilmDetails", "FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.FilmSuppliers", b =>
                {
                    b.HasOne("P06Shop.Shared.Shop.Film", "Film")
                        .WithMany("FilmSuppliers")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P06Shop.Shared.Shop.Supplier", "Supplier")
                        .WithMany("FilmSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.Category", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.Film", b =>
                {
                    b.Navigation("FilmDetails");

                    b.Navigation("FilmSuppliers");
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.Supplier", b =>
                {
                    b.Navigation("FilmSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
